version: "3.3"
services:
  nginx:
    image: nginx
    user: root
    volumes:
      - ./:/html
      - ./nginx.conf:/etc/nginx/conf.d/mysite.template
    working_dir: /
    expose:
      - "80"
    ports:
      - "443:80"
    command: /bin/bash -c "envsubst '$${API_LOCATION},$${UI_LOCATION}' < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"

  flask-server:
    image: python:3.6
    user: root
    volumes:
      - ./backend:/server
    working_dir: /server
    expose:
      - "5555"
    environment:
      - FLASK_APP=velocity_server.py
    command: /bin/bash -c "pip3 install -r requirements.txt && flask run --host=0.0.0.0 --port=5555"